---
# Install system packages

- name: Add Cloudera repository
  get_url:
    url=http://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list
    dest=/etc/apt/sources.list.d/cloudera_trusty.list

- name: Add line to apt sources.list for R version upgrade
  lineinfile:
    dest=/etc/apt/sources.list
    line="deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"

- name: Add Cloudera's apt key
  apt_key: url=http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key

- name: Add R apt key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

- name: Update APT cache
  apt: update_cache=yes

# Fix for munge incompatibility with 16.04, based on:
# https://github.com/gc3-uzh-ch/elasticluster/blob/989841fdccf9a59672a5d0a125878779debd3b99/elasticluster/share/playbooks/roles/slurm-common/tasks/munge.yml
- block:
    - name: Prevent MUNGE from starting
      command: systemctl mask munge.service
      args:
       creates: '/etc/systemd/system/munge.service'
    - name: Install MUNGE (Debian/Ubuntu)
      package:
        pkg=munge
        state=latest
    - name: Allow MUNGE to start
      command: systemctl unmask munge.service
      args:
        removes: /etc/systemd/system/munge.service
    - name: Add `--syslog` option to `munged` startup
      lineinfile:
        dest='/lib/systemd/system/munge.service'
        line='ExecStart=/usr/sbin/munged --syslog'
        regexp='^ExecStart=/usr/sbin/munged'
        state=present
    - name:  Reload systemd configuration
      command: systemctl daemon-reload
    - name: Ensure the MUNGE service is running
      service:
        name=munge
        enabled=yes
        state=started
  when: ansible_distribution_version >= "15.04"

# Keep ansible become/become_user happy when switching to unprivileged users
# see: http://stackoverflow.com/questions/36646880/ansible-2-1-0-using-become-become-user-fails-to-set-permissions-on-temp-file
- name: Install setfacl support
  become: yes
  apt: pkg=acl

- name: Install CloudMan-required system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ansible
    - automake  # s3fs required
    - build-essential  # s3fs required
    - cloudera-manager-daemons  # Cloudera Manager
    - cloudera-manager-server  # Cloudera Manager
    - cloudera-manager-agent  # Cloudera Manager
    - dkms  # AWS Enhanced Networking
    - fail2ban
    - fuse
    - glusterfs-client
    - jsvc  # Cloudgene required
    - libcurl4-openssl-dev  # s3fs required
    - libdatetime-perl
    - libfuse-dev  # s3fs required
    - libfuse2
    - libmysql-java  # Cloudera Manager required
    - libpcre3-dev
    - libreadline6-dev
    - libslurm-dev
    - libssl-dev
    - libtool  # s3fs required
    - libxml2-dev  # s3fs required
    - libmunge-dev
    - libyaml-dev
    - libwww-perl
    - linux-headers-4.8.0-41-lowlatency  # AWS Enhanced Networking
    - mime-support  # s3fs required
    - nfs-common
    - nfs-kernel-server
    - nodejs-legacy  # for IPython Interactive Environment
    - npm  # for IPython Interactive Environment
    - ntp  # Cloudera Manager required
    - nginx-extras
    - pkg-config
    - postgresql-server-dev-9.5
    - python-pip
    - python-tk  # for IPython %cpaste magic function
    - python-yaml
    - r-base
    - rabbitmq-server
    - screen
    - slurm-llnl
    - sshpass
    - uwsgi
    - uwsgi-plugin-python
    - xfsprogs
    - aptitude # to keep Ansible happy on Ubuntu >= 16.04

- name: Upgrade system packages
  apt: upgrade=yes
