---

- name: Check if swap file exists
  stat:
    path: "{{ cm_swap_file }}"
  register: swap_file_check

- name: Create swap file
  become: yes
  command: fallocate -l {{ cm_swap_space }} {{ cm_swap_file }}
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  become: yes
  file:
    path: "{{ cm_swap_file }}"
    mode: 0600

- name: Format swap file
  become: yes
  command: mkswap {{ cm_swap_file }}
  when: not swap_file_check.stat.exists

- name: Add to fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ cm_swap_file }}"
    line: "{{ cm_swap_file }} none swap sw 0 0"

- name: Turn on swap
  become: yes
  command: swapon -a

- name: Set swapiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: "1"
